### ISSUE TITLE
Did you try the same evaluation as doodle2search?

### ISSUE THREAD

**Issue by neouyghur** [ushasi/A-Simplified-framework-for-Zero-shot-Cross-Modal-Sketch-Data-Retrieval#2]
Hi thanks for your code, but I am afraid your evaluation protocla is unfair. Hope you can run the same evaluation as doodle2search. Thanks.

**Comment by ushasi** [comment]
HI,
We do not compare our results with Doodle2search as they use a different train-test split and protocol for training. Our experimental protocol is similar to that of their SEM-PCYC paper (note: same author as Doodle2search).
