### ISSUE TITLE
neccessary files missing

### ISSUE THREAD

**Issue by 1069066484** [ushasi/A-Simplified-framework-for-Zero-shot-Cross-Modal-Sketch-Data-Retrieval#3]
Thanks for your released code. We admire novelty of your work and wants to reproduce the results.
However, some ".mat" files (e.g. 'label_im.mat') seem missing in the "dataset" folder. 
Would you mind telling me how to access these files? Thanks.
 datasetX = scipy.io.loadmat('dataset/imagematnew.mat')
    photos = np.squeeze(datasetX['feature'])  
    datasetY = scipy.io.loadmat('dataset/sketchmatnew.mat')
    sketches = np.squeeze(datasetY['feature'])  
    label_im = scipy.io.loadmat('dataset/label_im.mat')
    label_im = np.squeeze(label_im['label_im'])  
    label_sk = scipy.io.loadmat('dataset/label_sk.mat')
    label_sk = np.squeeze(label_sk['label_sk'])  
    data1 = scipy.io.loadmat('dataset/names_images.mat')
    data1 = np.squeeze(data1['data'])  
    data2 = scipy.io.loadmat('dataset/names_sketches.mat')
    data2 = np.squeeze(data2['data3'])
    order = scipy.io.loadmat('dataset/dataset2.mat')
    order = np.squeeze(order['datamat2'])  
    dataset = scipy.io.loadmat('dataset/wv_embeddings.mat')
    wv = np.squeeze(dataset['features'])  # word2vec features multi-label
    dataset = scipy.io.loadmat('dataset/mst_graph.mat')

**Comment by ushasi** [comment]
Hi,
Yes, I could not upload these files to the GitHub repository due to space issues. The file sizes are large. However, I can provide the code for generating these features, so you can also generate these features for yourself for any dataset of your choice.

**Comment by ushasi** [comment]
I have added the VGG and Resnet-50 pre-train files so that imagematnew and sketchmatnew matfiles can be generated. Lable_im and label_sk are simple the class-wise one hot label files. So you would already have them for your dataset.

**Comment by ushasi** [comment]
The files names_images and names_sketches have been uploaded.
